Use ptr::wrapping_add to avoid may-dangle add UB
```
error: Undefined Behavior: in-bounds pointer arithmetic failed: alloc95118 has been freed, so this pointer is dangling
   --> src/refcount.rs:148:32
    |
148 |     [p as *const u32, unsafe { (p as *const u32).add(1) }]
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^ Undefined Behavior occurred here
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
help: alloc95118 was allocated here:
   --> tests/tests.rs:180:17
    |
180 |         let s = scope!();
    |                 ^^^^^^^^
help: alloc95118 was deallocated here:
   --> tests/tests.rs:188:5
    |
188 |     }
    |     ^
    = note: this is on thread `unnamed-13`
    = note: stack backtrace:
            0: lien::refcount::words
                at src/refcount.rs:148:32: 148:56
            1: lien::refcount::lo_ptr
                at src/refcount.rs:159:50: 159:58
            2: lien::refcount::wake_hi_lo::<fn(*const u32) {lien::refcount::imp::wake32}>
                at src/refcount.rs:192:41: 192:52
            3: lien::refcount::imp::wake
                at src/refcount/miri.rs:31:42: 31:77
            4: lien::__Rc::dec
                at src/refcount.rs:136:9: 136:43
            5: <lien::Lien as std::ops::Drop>::drop
                at src/lib.rs:148:18: 148:45
            6: std::ptr::drop_in_place::<lien::Lien> - shim(Some(lien::Lien))
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:809:1: 811:25
            7: std::ptr::drop_in_place::<lien::RefMut<i32>> - shim(Some(lien::RefMut<i32>))
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:809:1: 811:25
            8: std::mem::drop::<lien::RefMut<i32>>
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:1004:1: 1004:2
            9: scope_blocks_until_lien_dropped_by_thread::{closure#0}
                at tests/tests.rs:186:13: 186:20
note: the last function in that backtrace got called indirectly due to this code
   --> tests/tests.rs:182:9
    |
182 | /         std::thread::spawn(move || {
183 | |             std::thread::sleep(Duration::from_millis(100));
184 | |             assert_eq!(*r, 42);
185 | |             flag2.store(true, Ordering::Release);
186 | |             drop(r);
187 | |         });
    | |__________^
    = note: this error originates in the macro `scope` (in Nightly builds, run with -Z macro-backtrace for more info)
```